# Replace the "❯" symbol in the prompt with "➜"
#[character]
# success_symbol = "[➜](bold green) "
#error_symbol = "[➜](bold red) "

# custom vim mode
# vicmd_symbol = "[V](bold green) "
vicmd_symbol = "[V] "

# conda env
[conda]
format = "[$symbol$environment](dimmed green) "

# gcloud env
[gcloud]
format = "[$symbol $active]($style) "
style = "bold yellow"
disabled = true

